version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    volumes:
      - ./FullStack_Proof:/app 
  mongo:
    image: mongo
    ports:
      - "27017:27017"

